export const SET_SUGGESTED_MOVIES = 'SET_SUGGESTED_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';
export const SET_SINGLE_MOVIE = 'SET_SINGLE_MOVIE';
export const SET_BACK_TO_HOME = 'SET_BACK_TO_HOME';
export const SET_RATING_FILTER = "SET_RATING_FILTER";